# Generated by Django 5.2.8 on 2026-04-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_socialusers_provider_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(choices=[("M", "남성"), ("F", "여성")], max_length=6, null=True),
        ),
    ]
