# Generated by Django 5.2.8 on 2026-04-21 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=50)),
                ("thumbnail_image_url", models.ImageField(default="default_img_url", max_length=255, upload_to="")),
            ],
            options={
                "db_table": "exams",
            },
        ),
        migrations.CreateModel(
            name="ExamDeployment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("duration_time", models.SmallIntegerField(max_length=2)),
                ("access_code", models.CharField(max_length=64)),
                ("open_at", models.DateTimeField(blank=True, null=True)),
                ("close_at", models.DateTimeField(blank=True, null=True)),
                ("question_snapshot_json", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(choices=[("activate", "활성화"), ("deactivate", "비활성화")], max_length=10),
                ),
                ("exam", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="exams.exam")),
            ],
            options={
                "db_table": "exam_deployments",
            },
        ),
        migrations.CreateModel(
            name="ExamQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question", models.CharField(max_length=255)),
                ("prompt", models.TextField(blank=True, null=True)),
                ("blank_count", models.SmallIntegerField(blank=True, max_length=1, null=True)),
                ("optional_json", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("blank", "빈칸채우기"),
                            ("sort", "순서정렬"),
                            ("choice", "다지선다"),
                            ("sentence", "주관식"),
                            ("word", "단답형"),
                            ("quiz", "OX퀴즈"),
                        ]
                    ),
                ),
                ("answer", models.JSONField(default=dict)),
                ("point", models.SmallIntegerField(max_length=2)),
                ("explantation", models.TextField(default="")),
                ("exam", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="exams.exam")),
            ],
            options={
                "db_table": "exam_questions",
            },
        ),
        migrations.CreateModel(
            name="ExamSubmission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField()),
                ("cheating_count", models.SmallIntegerField(max_length=1)),
                ("answer_json", models.JSONField(default=dict)),
                ("score", models.SmallIntegerField()),
                ("correct_answer_count", models.SmallIntegerField()),
                (
                    "deployment",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="exams.examdeployment"),
                ),
                (
                    "submitter",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "db_table": "exam_submissions",
            },
        ),
    ]
