# Generated by Django 5.2.8 on 2026-04-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="examdeployment",
            old_name="exam_id",
            new_name="exam",
        ),
        migrations.RenameField(
            model_name="examquestion",
            old_name="exam_id",
            new_name="exam",
        ),
        migrations.RenameField(
            model_name="examsubmission",
            old_name="deployment_id",
            new_name="deployment",
        ),
        migrations.RenameField(
            model_name="examsubmission",
            old_name="submitter_id",
            new_name="submitter",
        ),
        migrations.AlterField(
            model_name="exam",
            name="thumbnail_image_url",
            field=models.CharField(default="default_img_url", max_length=255),
        ),
        migrations.AlterField(
            model_name="examquestion",
            name="explantation",
            field=models.TextField(default=""),
        ),
    ]
