# Generated by Django 5.2.8 on 2026-04-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0002_rename_exam_id_examdeployment_exam_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examquestion",
            name="type",
            field=models.CharField(
                choices=[
                    ("blank", "빈칸채우기"),
                    ("sort", "순서정렬"),
                    ("choice", "다지선다"),
                    ("sentence", "주관식"),
                    ("word", "단답형"),
                    ("quiz", "OX퀴즈"),
                ],
                max_length=10,
            ),
        ),
    ]
